version: '3.8'

services:
  backend-app:
    build:
      context: .
    container_name: nxz-backend-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
